export interface Service {
  id: string;
  name: string;
  slug: string; // Simple Icons slug
  domain: string; // For Brandfetch/Clearbit
  category: 'AI & LLMs' | 'Adobe' | 'Design' | 'Dev' | 'Productivity' | 'Learning' | 'Entertainment' | 'Google' | 'Social' | 'Finance' | 'Utilities' | 'AI Generation';
  color?: string;
}

export const GLOBAL_SERVICES: Service[] = [
  // AI & LLMs (Chat & Reasoning)
  { id: 'openai', name: 'ChatGPT (OpenAI)', slug: 'openai', domain: 'openai.com', category: 'AI & LLMs', color: '000000' },
  { id: 'anthropic', name: 'Claude (Anthropic)', slug: 'anthropic', domain: 'anthropic.com', category: 'AI & LLMs', color: 'D97757' },
  { id: 'gemini-advanced', name: 'Google Gemini Advanced', slug: 'googlegemini', domain: 'gemini.google.com', category: 'AI & LLMs', color: '4285F4' },
  { id: 'perplexity', name: 'Perplexity AI', slug: 'perplexity', domain: 'perplexity.ai', category: 'AI & LLMs', color: '20B2AA' },
  { id: 'mistral', name: 'Mistral AI', slug: 'mistral', domain: 'mistral.ai', category: 'AI & LLMs', color: '000000' },
  { id: 'deepseek', name: 'DeepSeek', slug: 'deepseek', domain: 'deepseek.com', category: 'AI & LLMs', color: '4D6BFE' },
  { id: 'grok', name: 'Grok (xAI)', slug: 'x', domain: 'x.ai', category: 'AI & LLMs', color: '000000' },
  { id: 'jasper', name: 'Jasper AI', slug: 'jasper', domain: 'jasper.ai', category: 'AI & LLMs', color: 'FF4F5E' },
  { id: 'poe', name: 'Poe (Quora)', slug: 'poe', domain: 'poe.com', category: 'AI & LLMs', color: '000000' },
  { id: 'character-ai', name: 'Character.ai', slug: 'character', domain: 'character.ai', category: 'AI & LLMs', color: '000000' },
  { id: 'copy-ai', name: 'Copy.ai', slug: 'copyai', domain: 'copy.ai', category: 'AI & LLMs', color: '252422' },
  { id: 'writesonic', name: 'Writesonic', slug: 'writesonic', domain: 'writesonic.com', category: 'AI & LLMs', color: '000000' },
  { id: 'phind', name: 'Phind', slug: 'phind', domain: 'phind.com', category: 'AI & LLMs', color: '000000' },

  // AI Generation (Visual & Creative)
  { id: 'midjourney', name: 'Midjourney', slug: 'midjourney', domain: 'midjourney.com', category: 'AI Generation', color: 'FFFFFF' },
  { id: 'runway', name: 'Runway AI', slug: 'runway', domain: 'runwayml.com', category: 'AI Generation', color: 'FFFFFF' },
  { id: 'pika', name: 'Pika Labs', slug: 'pika', domain: 'pika.art', category: 'AI Generation', color: 'FFFFFF' },
  { id: 'leonardo', name: 'Leonardo.ai', slug: 'leonardoai', domain: 'leonardo.ai', category: 'AI Generation', color: 'FFFFFF' },
  { id: 'freepik', name: 'Freepik', slug: 'freepik', domain: 'freepik.com', category: 'AI Generation', color: '0066FF' },
  { id: 'higgsfield', name: 'Higgsfield AI', slug: 'higgsfield', domain: 'higgsfield.ai', category: 'AI Generation', color: 'FFFFFF' },
  { id: 'comfyui', name: 'ComfyUI', slug: 'comfyui', domain: 'comfy.org', category: 'AI Generation', color: 'FFFFFF' },
  { id: 'nordy-ai', name: 'Nordy AI', slug: 'nordy', domain: 'nordy.ai', category: 'AI Generation', color: 'FFFFFF' },
  { id: 'luma-ai', name: 'Luma AI', slug: 'lumaai', domain: 'lumalabs.ai', category: 'AI Generation', color: 'FFFFFF' },
  { id: 'heygen', name: 'HeyGen', slug: 'heygen', domain: 'heygen.com', category: 'AI Generation', color: 'FF5C5C' },
  { id: 'elevenlabs', name: 'ElevenLabs', slug: 'elevenlabs', domain: 'elevenlabs.io', category: 'AI Generation', color: '000000' },
  { id: 'suno', name: 'Suno AI', slug: 'suno', domain: 'suno.com', category: 'AI Generation', color: '000000' },
  { id: 'udio', name: 'Udio', slug: 'udio', domain: 'udio.com', category: 'AI Generation', color: '000000' },
  { id: 'descript', name: 'Descript', slug: 'descript', domain: 'descript.com', category: 'AI Generation', color: '000000' },
  { id: 'captions', name: 'Captions.ai', slug: 'captions', domain: 'captions.ai', category: 'AI Generation', color: '000000' },
  { id: 'synthesia', name: 'Synthesia', slug: 'synthesia', domain: 'synthesia.io', category: 'AI Generation', color: '000000' },
  { id: 'invideo', name: 'InVideo AI', slug: 'invideo', domain: 'invideo.io', category: 'AI Generation', color: '000000' },
  { id: 'pictory', name: 'Pictory', slug: 'pictory', domain: 'pictory.ai', category: 'AI Generation', color: '000000' },
  { id: 'kling-ai', name: 'Kling AI', slug: 'klingai', domain: 'klingai.com', category: 'AI Generation', color: 'FFFFFF' },
  { id: 'hailuo-ai', name: 'Hailuo AI', slug: 'hailuoai', domain: 'hailuoai.com', category: 'AI Generation', color: 'FFFFFF' },
  { id: 'genmo', name: 'Genmo (Mochi)', slug: 'genmo', domain: 'genmo.ai', category: 'AI Generation', color: 'FFFFFF' },
  { id: 'black-forest-labs', name: 'Black Forest Labs (Flux)', slug: 'blackforestlabs', domain: 'blackforestlabs.ai', category: 'AI Generation', color: 'FFFFFF' },
  { id: 'recraft', name: 'Recraft', slug: 'recraft', domain: 'recraft.ai', category: 'AI Generation', color: 'FFFFFF' },
  { id: 'viggle', name: 'Viggle AI', slug: 'viggle', domain: 'viggle.ai', category: 'AI Generation', color: 'FFFFFF' },
  { id: 'hedra', name: 'Hedra', slug: 'hedra', domain: 'hedra.com', category: 'AI Generation', color: 'FFFFFF' },

  // Adobe Design Programs
  { id: 'adobe-creative-cloud', name: 'Adobe Creative Cloud', slug: 'adobecreativecloud', domain: 'adobe.com', category: 'Adobe', color: 'DA1F26' },
  { id: 'adobe-photoshop', name: 'Adobe Photoshop', slug: 'adobephotoshop', domain: 'adobe.com', category: 'Adobe', color: '31A8FF' },
  { id: 'adobe-illustrator', name: 'Adobe Illustrator', slug: 'adobeillustrator', domain: 'adobe.com', category: 'Adobe', color: 'FF9A00' },
  { id: 'adobe-after-effects', name: 'Adobe After Effects', slug: 'adobeaftereffects', domain: 'adobe.com', category: 'Adobe', color: 'CF96FD' },
  { id: 'adobe-premiere', name: 'Adobe Premiere Pro', slug: 'adobepremierepro', domain: 'adobe.com', category: 'Adobe', color: 'EA77FF' },
  { id: 'adobe-lightroom', name: 'Adobe Lightroom', slug: 'adobelightroom', domain: 'adobe.com', category: 'Adobe', color: '31A8FF' },
  { id: 'adobe-indesign', name: 'Adobe InDesign', slug: 'adobeindesign', domain: 'adobe.com', category: 'Adobe', color: 'FF3366' },
  { id: 'adobe-xd', name: 'Adobe XD', slug: 'adobexd', domain: 'adobe.com', category: 'Adobe', color: 'FF61F6' },
  { id: 'adobe-audition', name: 'Adobe Audition', slug: 'adobeaudition', domain: 'adobe.com', category: 'Adobe', color: '00E5B3' },
  { id: 'adobe-acrobat', name: 'Adobe Acrobat Pro', slug: 'adobeacrobatreader', domain: 'adobe.com', category: 'Adobe', color: 'EC1C24' },
  { id: 'adobe-dreamweaver', name: 'Adobe Dreamweaver', slug: 'adobedreamweaver', domain: 'adobe.com', category: 'Adobe', color: 'FF00FF' },
  { id: 'adobe-animate', name: 'Adobe Animate', slug: 'adobeanimate', domain: 'adobe.com', category: 'Adobe', color: 'FF0000' },
  { id: 'adobe-fresco', name: 'Adobe Fresco', slug: 'adobefresco', domain: 'adobe.com', category: 'Adobe', color: 'FF9A00' },
  { id: 'adobe-bridge', name: 'Adobe Bridge', slug: 'adobebridge', domain: 'adobe.com', category: 'Adobe', color: 'FF9A00' },

  // Design & Creative
  { id: 'figma', name: 'Figma', slug: 'figma', domain: 'figma.com', category: 'Design', color: 'F24E1E' },
  { id: 'canva', name: 'Canva', slug: 'canva', domain: 'canva.com', category: 'Design', color: '00C4CC' },
  { id: 'framer', name: 'Framer', slug: 'framer', domain: 'framer.com', category: 'Design', color: '0055FF' },
  { id: 'webflow', name: 'Webflow', slug: 'webflow', domain: 'webflow.com', category: 'Design', color: '4353FF' },
  { id: 'spline', name: 'Spline 3D', slug: 'spline', domain: 'spline.design', category: 'Design', color: 'FFFFFF' },
  { id: 'envato', name: 'Envato Elements', slug: 'envato', domain: 'elements.envato.com', category: 'Design', color: '81B441' },
  { id: 'dribbble', name: 'Dribbble Pro', slug: 'dribbble', domain: 'dribbble.com', category: 'Design', color: 'EA4C89' },
  { id: 'behance', name: 'Behance', slug: 'behance', domain: 'behance.net', category: 'Design', color: '1769FF' },
  { id: 'sketch', name: 'Sketch', slug: 'sketch', domain: 'sketch.com', category: 'Design', color: 'F7B500' },
  { id: 'affinity-photo', name: 'Affinity Photo', slug: 'affinityphoto', domain: 'affinity.serif.com', category: 'Design', color: '3A4EAF' },
  { id: 'affinity-designer', name: 'Affinity Designer', slug: 'affinitydesigner', domain: 'affinity.serif.com', category: 'Design', color: '009EDA' },
  { id: 'affinity-publisher', name: 'Affinity Publisher', slug: 'affinitypublisher', domain: 'affinity.serif.com', category: 'Design', color: 'F13C20' },
  { id: 'procreate', name: 'Procreate', slug: 'procreate', domain: 'procreate.com', category: 'Design', color: '000000' },
  { id: 'pixlr', name: 'Pixlr', slug: 'pixlr', domain: 'pixlr.com', category: 'Design', color: '00C4CC' },
  { id: 'photopea', name: 'Photopea', slug: 'photopea', domain: 'photopea.com', category: 'Design', color: '000000' },
  { id: 'creative-market', name: 'Creative Market', slug: 'creativemarket', domain: 'creativemarket.com', category: 'Design', color: '000000' },
  { id: 'shutterstock', name: 'Shutterstock', slug: 'shutterstock', domain: 'shutterstock.com', category: 'Design', color: 'EE2B24' },
  { id: 'getty-images', name: 'Getty Images', slug: 'gettyimages', domain: 'gettyimages.com', category: 'Design', color: '000000' },

  // Google Ecosystem
  { id: 'google-one', name: 'Google One', slug: 'google', domain: 'one.google.com', category: 'Google', color: '4285F4' },
  { id: 'google-workspace', name: 'Google Workspace', slug: 'googleworkspace', domain: 'workspace.google.com', category: 'Google', color: '4285F4' },
  { id: 'google-cloud', name: 'Google Cloud', slug: 'googlecloud', domain: 'cloud.google.com', category: 'Google', color: '4285F4' },
  { id: 'google-photos', name: 'Google Photos', slug: 'googlephotos', domain: 'photos.google.com', category: 'Google', color: '4285F4' },
  { id: 'google-drive', name: 'Google Drive', slug: 'googledrive', domain: 'drive.google.com', category: 'Google', color: '4285F4' },
  { id: 'youtube-music', name: 'YouTube Music', slug: 'youtubemusic', domain: 'music.youtube.com', category: 'Google', color: 'FF0000' },
  { id: 'google-ads', name: 'Google Ads', slug: 'googleads', domain: 'ads.google.com', category: 'Google', color: '4285F4' },
  { id: 'google-analytics', name: 'Google Analytics', slug: 'googleanalytics', domain: 'analytics.google.com', category: 'Google', color: 'E37400' },
  { id: 'google-domains', name: 'Google Domains', slug: 'googledomains', domain: 'domains.google.com', category: 'Google', color: '4285F4' },
  { id: 'google-play-pass', name: 'Google Play Pass', slug: 'googleplay', domain: 'play.google.com', category: 'Google', color: '4285F4' },
  { id: 'google-keep', name: 'Google Keep', slug: 'googlekeep', domain: 'keep.google.com', category: 'Google', color: 'FBBC04' },
  { id: 'google-tasks', name: 'Google Tasks', slug: 'googletasks', domain: 'tasks.google.com', category: 'Google', color: '4285F4' },

  // Tech & Dev
  { id: 'github', name: 'GitHub Copilot', slug: 'github', domain: 'github.com', category: 'Dev', color: '181717' },
  { id: 'vercel', name: 'Vercel Pro', slug: 'vercel', domain: 'vercel.com', category: 'Dev', color: '000000' },
  { id: 'cursor', name: 'Cursor AI', slug: 'cursor', domain: 'cursor.com', category: 'Dev', color: 'FFFFFF' },
  { id: 'replit', name: 'Replit', slug: 'replit', domain: 'replit.com', category: 'Dev', color: 'F26207' },
  { id: 'netlify', name: 'Netlify', slug: 'netlify', domain: 'netlify.com', category: 'Dev', color: '00C7B7' },
  { id: 'digitalocean', name: 'DigitalOcean', slug: 'digitalocean', domain: 'digitalocean.com', category: 'Dev', color: '0080FF' },
  { id: 'aws', name: 'AWS', slug: 'amazonwebservices', domain: 'aws.amazon.com', category: 'Dev', color: '232F3E' },
  { id: 'azure', name: 'Microsoft Azure', slug: 'microsoftazure', domain: 'azure.microsoft.com', category: 'Dev', color: '0089D6' },
  { id: 'heroku', name: 'Heroku', slug: 'heroku', domain: 'heroku.com', category: 'Dev', color: '430098' },
  { id: 'cloudflare', name: 'Cloudflare', slug: 'cloudflare', domain: 'cloudflare.com', category: 'Dev', color: 'F38020' },
  { id: 'mongodb', name: 'MongoDB Atlas', slug: 'mongodb', domain: 'mongodb.com', category: 'Dev', color: '47A248' },
  { id: 'supabase', name: 'Supabase', slug: 'supabase', domain: 'supabase.com', category: 'Dev', color: '3ECF8E' },
  { id: 'firebase', name: 'Firebase', slug: 'firebase', domain: 'firebase.google.com', category: 'Dev', color: 'FFCA28' },
  { id: 'docker', name: 'Docker Business', slug: 'docker', domain: 'docker.com', category: 'Dev', color: '2496ED' },
  { id: 'postman', name: 'Postman', slug: 'postman', domain: 'postman.com', category: 'Dev', color: 'FF6C37' },
  { id: 'stack-overflow', name: 'Stack Overflow for Teams', slug: 'stackoverflow', domain: 'stackoverflow.com', category: 'Dev', color: 'F48024' },
  { id: 'gitkraken', name: 'GitKraken', slug: 'gitkraken', domain: 'gitkraken.com', category: 'Dev', color: '1793D1' },
  { id: 'jetbrains', name: 'JetBrains All Products', slug: 'jetbrains', domain: 'jetbrains.com', category: 'Dev', color: '000000' },
  { id: 'planetscale', name: 'PlanetScale', slug: 'planetscale', domain: 'planetscale.com', category: 'Dev', color: '000000' },
  { id: 'sentry', name: 'Sentry', slug: 'sentry', domain: 'sentry.io', category: 'Dev', color: '362D59' },
  { id: 'datadog', name: 'Datadog', slug: 'datadog', domain: 'datadog.com', category: 'Dev', color: '632CA6' },
  { id: 'new-relic', name: 'New Relic', slug: 'newrelic', domain: 'newrelic.com', category: 'Dev', color: '008C99' },
  { id: 'pagerduty', name: 'PagerDuty', slug: 'pagerduty', domain: 'pagerduty.com', category: 'Dev', color: '06AC38' },

  // Productivity
  { id: 'notion', name: 'Notion Plus', slug: 'notion', domain: 'notion.so', category: 'Productivity', color: '000000' },
  { id: 'slack', name: 'Slack Pro', slug: 'slack', domain: 'slack.com', category: 'Productivity', color: '4A154B' },
  { id: 'zoom', name: 'Zoom Pro', slug: 'zoom', domain: 'zoom.us', category: 'Productivity', color: '2D8CFF' },
  { id: 'trello', name: 'Trello', slug: 'trello', domain: 'trello.com', category: 'Productivity', color: '0079BF' },
  { id: 'asana', name: 'Asana', slug: 'asana', domain: 'asana.com', category: 'Productivity', color: 'F0642F' },
  { id: 'monday', name: 'Monday.com', slug: 'mondaydotcom', domain: 'monday.com', category: 'Productivity', color: 'FF3D57' },
  { id: 'clickup', name: 'ClickUp', slug: 'clickup', domain: 'clickup.com', category: 'Productivity', color: '7B68EE' },
  { id: 'todoist', name: 'Todoist', slug: 'todoist', domain: 'todoist.com', category: 'Productivity', color: 'E44332' },
  { id: 'evernote', name: 'Evernote', slug: 'evernote', domain: 'evernote.com', category: 'Productivity', color: '00A82D' },
  { id: 'microsoft-365', name: 'Microsoft 365', slug: 'microsoft365', domain: 'microsoft.com', category: 'Productivity', color: 'EB3C00' },
  { id: 'dropbox', name: 'Dropbox', slug: 'dropbox', domain: 'dropbox.com', category: 'Productivity', color: '0061FF' },
  { id: 'box', name: 'Box', slug: 'box', domain: 'box.com', category: 'Productivity', color: '0061D5' },
  { id: 'hexfield', name: 'Hexfield', slug: 'hex', domain: 'hex.tech', category: 'Productivity', color: '000000' },
  { id: 'calendly', name: 'Calendly', slug: 'calendly', domain: 'calendly.com', category: 'Productivity', color: '006BFF' },
  { id: 'loom', name: 'Loom', slug: 'loom', domain: 'loom.com', category: 'Productivity', color: '625DF5' },
  { id: 'miro', name: 'Miro', slug: 'miro', domain: 'miro.com', category: 'Productivity', color: '050038' },
  { id: 'linear', name: 'Linear', slug: 'linear', domain: 'linear.app', category: 'Productivity', color: '5E6AD2' },
  { id: 'raycast', name: 'Raycast Pro', slug: 'raycast', domain: 'raycast.com', category: 'Productivity', color: 'FF6363' },
  { id: 'obsidian', name: 'Obsidian Sync', slug: 'obsidian', domain: 'obsidian.md', category: 'Productivity', color: '483699' },
  { id: 'craft', name: 'Craft Docs', slug: 'craft', domain: 'craft.do', category: 'Productivity', color: '000000' },
  { id: 'superhuman', name: 'Superhuman', slug: 'superhuman', domain: 'superhuman.com', category: 'Productivity', color: '000000' },
  { id: 'spark-mail', name: 'Spark Mail', slug: 'spark', domain: 'sparkmailapp.com', category: 'Productivity', color: '007AFF' },
  { id: 'fantastical', name: 'Fantastical', slug: 'flexibits', domain: 'flexibits.com', category: 'Productivity', color: 'E33C2A' },
  { id: 'airtable', name: 'Airtable', slug: 'airtable', domain: 'airtable.com', category: 'Productivity', color: '18BFFF' },
  { id: 'coda', name: 'Coda', slug: 'coda', domain: 'coda.io', category: 'Productivity', color: 'F34B58' },
  { id: 'basecamp', name: 'Basecamp', slug: 'basecamp', domain: 'basecamp.com', category: 'Productivity', color: '22AF6D' },
  { id: 'ticktick', name: 'TickTick Premium', slug: 'ticktick', domain: 'ticktick.com', category: 'Productivity', color: 'FF8C00' },
  { id: 'things', name: 'Things 3', slug: 'things', domain: 'culturedcode.com', category: 'Productivity', color: '27A1E5' },
  { id: 'todoist-pro', name: 'Todoist Pro', slug: 'todoist', domain: 'todoist.com', category: 'Productivity', color: 'E44332' },
  { id: 'anydo', name: 'Any.do Premium', slug: 'anydo', domain: 'any.do', category: 'Productivity', color: '0085FF' },
  { id: 'pcloud', name: 'pCloud', slug: 'pcloud', domain: 'pcloud.com', category: 'Productivity', color: '00ADEF' },

  // Learning (LMS)
  { id: 'coursera', name: 'Coursera', slug: 'coursera', domain: 'coursera.org', category: 'Learning', color: '0056D2' },
  { id: 'udemy', name: 'Udemy', slug: 'udemy', domain: 'udemy.com', category: 'Learning', color: 'A435F0' },
  { id: 'skillshare', name: 'Skillshare', slug: 'skillshare', domain: 'skillshare.com', category: 'Learning', color: '00FF84' },
  { id: 'masterclass', name: 'MasterClass', slug: 'masterclass', domain: 'masterclass.com', category: 'Learning', color: '000000' },
  { id: 'duolingo', name: 'Duolingo Plus', slug: 'duolingo', domain: 'duolingo.com', category: 'Learning', color: '58CC02' },
  { id: 'babbel', name: 'Babbel', slug: 'babbel', domain: 'babbel.com', category: 'Learning', color: 'FF7F40' },
  { id: 'linkedin-learning', name: 'LinkedIn Learning', slug: 'linkedin', domain: 'linkedin.com/learning', category: 'Learning', color: '0A66C2' },
  { id: 'brilliant', name: 'Brilliant.org', slug: 'brilliant', domain: 'brilliant.org', category: 'Learning', color: '000000' },
  { id: 'codecademy', name: 'Codecademy', slug: 'codecademy', domain: 'codecademy.com', category: 'Learning', color: '303347' },
  { id: 'pluralsight', name: 'Pluralsight', slug: 'pluralsight', domain: 'pluralsight.com', category: 'Learning', color: 'F15B2B' },
  { id: 'datacamp', name: 'DataCamp', slug: 'datacamp', domain: 'datacamp.com', category: 'Learning', color: '05192D' },
  { id: 'frontend-masters', name: 'Frontend Masters', slug: 'frontendmasters', domain: 'frontendmasters.com', category: 'Learning', color: 'C02D2F' },

  // Entertainment
  { id: 'netflix', name: 'Netflix', slug: 'netflix', domain: 'netflix.com', category: 'Entertainment', color: 'E50914' },
  { id: 'spotify', name: 'Spotify Premium', slug: 'spotify', domain: 'spotify.com', category: 'Entertainment', color: '1DB954' },
  { id: 'disney-plus', name: 'Disney+', slug: 'disneyplus', domain: 'disneyplus.com', category: 'Entertainment', color: '113CCF' },
  { id: 'hulu', name: 'Hulu', slug: 'hulu', domain: 'hulu.com', category: 'Entertainment', color: '1CE783' },
  { id: 'hbo-max', name: 'HBO Max', slug: 'hbo', domain: 'hbomax.com', category: 'Entertainment', color: '000000' },
  { id: 'paramount-plus', name: 'Paramount+', slug: 'paramountplus', domain: 'paramountplus.com', category: 'Entertainment', color: '0064FF' },
  { id: 'apple-tv-plus', name: 'Apple TV+', slug: 'appletv', domain: 'tv.apple.com', category: 'Entertainment', color: '000000' },
  { id: 'amazon-prime-video', name: 'Prime Video', slug: 'primevideo', domain: 'primevideo.com', category: 'Entertainment', color: '00A8E1' },
  { id: 'twitch', name: 'Twitch Turbo', slug: 'twitch', domain: 'twitch.tv', category: 'Entertainment', color: '9146FF' },
  { id: 'crunchyroll', name: 'Crunchyroll Premium', slug: 'crunchyroll', domain: 'crunchyroll.com', category: 'Entertainment', color: 'F47521' },
  { id: 'audible', name: 'Audible Premium Plus', slug: 'audible', domain: 'audible.com', category: 'Entertainment', color: 'F1911E' },
  { id: 'tidal', name: 'Tidal HiFi', slug: 'tidal', domain: 'tidal.com', category: 'Entertainment', color: '000000' },
  { id: 'nintendo-switch-online', name: 'Nintendo Switch Online', slug: 'nintendoswitch', domain: 'nintendo.com', category: 'Entertainment', color: 'E60012' },
  { id: 'playstation-plus', name: 'PlayStation Plus', slug: 'playstation', domain: 'playstation.com', category: 'Entertainment', color: '003791' },
  { id: 'xbox-game-pass', name: 'Xbox Game Pass', slug: 'xbox', domain: 'xbox.com', category: 'Entertainment', color: '107C10' },
  { id: 'apple-music', name: 'Apple Music', slug: 'applemusic', domain: 'music.apple.com', category: 'Entertainment', color: 'FA243C' },
  { id: 'deezer', name: 'Deezer Premium', slug: 'deezer', domain: 'deezer.com', category: 'Entertainment', color: '000000' },
  { id: 'soundcloud', name: 'SoundCloud Go+', slug: 'soundcloud', domain: 'soundcloud.com', category: 'Entertainment', color: 'FF3300' },
  { id: 'discovery-plus', name: 'Discovery+', slug: 'discoveryplus', domain: 'discoveryplus.com', category: 'Entertainment', color: '000000' },
  { id: 'peacock', name: 'Peacock Premium', slug: 'peacock', domain: 'peacocktv.com', category: 'Entertainment', color: '000000' },
  { id: 'mubi', name: 'MUBI', slug: 'mubi', domain: 'mubi.com', category: 'Entertainment', color: '000000' },
  { id: 'youtube-premium', name: 'YouTube Premium', slug: 'youtube', domain: 'youtube.com', category: 'Entertainment', color: 'FF0000' },

  // Social
  { id: 'x-premium', name: 'X Premium', slug: 'x', domain: 'x.com', category: 'Social', color: '000000' },
  { id: 'linkedin-premium', name: 'LinkedIn Premium', slug: 'linkedin', domain: 'linkedin.com', category: 'Social', color: '0A66C2' },
  { id: 'instagram', name: 'Instagram Meta Verified', slug: 'instagram', domain: 'instagram.com', category: 'Social', color: 'E4405F' },
  { id: 'facebook', name: 'Facebook Meta Verified', slug: 'facebook', domain: 'facebook.com', category: 'Social', color: '1877F2' },
  { id: 'tiktok', name: 'TikTok', slug: 'tiktok', domain: 'tiktok.com', category: 'Social', color: '000000' },
  { id: 'pinterest', name: 'Pinterest', slug: 'pinterest', domain: 'pinterest.com', category: 'Social', color: 'BD081C' },
  { id: 'reddit-premium', name: 'Reddit Premium', slug: 'reddit', domain: 'reddit.com', category: 'Social', color: 'FF4500' },
  { id: 'discord-nitro', name: 'Discord Nitro', slug: 'discord', domain: 'discord.com', category: 'Social', color: '5865F2' },
  { id: 'snapchat-plus', name: 'Snapchat+', slug: 'snapchat', domain: 'snapchat.com', category: 'Social', color: 'FFFC00' },
  { id: 'medium', name: 'Medium Membership', slug: 'medium', domain: 'medium.com', category: 'Social', color: '000000' },
  { id: 'substack', name: 'Substack', slug: 'substack', domain: 'substack.com', category: 'Social', color: 'FF6719' },
  { id: 'patreon', name: 'Patreon', slug: 'patreon', domain: 'patreon.com', category: 'Social', color: 'FF424D' },
  { id: 'onlyfans', name: 'OnlyFans', slug: 'onlyfans', domain: 'onlyfans.com', category: 'Social', color: '008AFF' },
  { id: 'strava', name: 'Strava Subscription', slug: 'strava', domain: 'strava.com', category: 'Social', color: 'FC4C02' },
  { id: 'tinder-gold', name: 'Tinder Gold', slug: 'tinder', domain: 'tinder.com', category: 'Social', color: 'FE3C72' },
  { id: 'bumble-premium', name: 'Bumble Premium', slug: 'bumble', domain: 'bumble.com', category: 'Social', color: 'FFCB37' },
  { id: 'hinge-plus', name: 'Hinge+', slug: 'hinge', domain: 'hinge.co', category: 'Social', color: '000000' },
  { id: 'bereal', name: 'BeReal', slug: 'bereal', domain: 'bereal.com', category: 'Social', color: '000000' },
  { id: 'threads', name: 'Threads', slug: 'threads', domain: 'threads.net', category: 'Social', color: '000000' },
  { id: 'bluesky', name: 'Bluesky', slug: 'bluesky', domain: 'bsky.app', category: 'Social', color: '0085FF' },
  { id: 'telegram-premium', name: 'Telegram Premium', slug: 'telegram', domain: 'telegram.org', category: 'Social', color: '26A5E4' },
  { id: 'whatsapp-business', name: 'WhatsApp Business', slug: 'whatsapp', domain: 'whatsapp.com', category: 'Social', color: '25D366' },

  // Finance
  { id: 'stripe', name: 'Stripe', slug: 'stripe', domain: 'stripe.com', category: 'Finance', color: '008CDD' },
  { id: 'paypal', name: 'PayPal', slug: 'paypal', domain: 'paypal.com', category: 'Finance', color: '003087' },
  { id: 'revolut', name: 'Revolut', slug: 'revolut', domain: 'revolut.com', category: 'Finance', color: '000000' },
  { id: 'wise', name: 'Wise', slug: 'wise', domain: 'wise.com', category: 'Finance', color: '00B9FF' },
  { id: 'monzo', name: 'Monzo', slug: 'monzo', domain: 'monzo.com', category: 'Finance', color: 'FF4F5E' },
  { id: 'starling', name: 'Starling Bank', slug: 'starlingbank', domain: 'starlingbank.com', category: 'Finance', color: '6935D3' },
  { id: 'n26', name: 'N26', slug: 'n26', domain: 'n26.com', category: 'Finance', color: '36A18B' },
  { id: 'robinhood', name: 'Robinhood Gold', slug: 'robinhood', domain: 'robinhood.com', category: 'Finance', color: '00C805' },
  { id: 'coinbase', name: 'Coinbase One', slug: 'coinbase', domain: 'coinbase.com', category: 'Finance', color: '0052FF' },
  { id: 'binance', name: 'Binance', slug: 'binance', domain: 'binance.com', category: 'Finance', color: 'F3BA2F' },
  { id: 'tradingview', name: 'TradingView', slug: 'tradingview', domain: 'tradingview.com', category: 'Finance', color: '131722' },
  { id: 'mint', name: 'Mint', slug: 'mint', domain: 'mint.intuit.com', category: 'Finance', color: '00D1C1' },
  { id: 'ynab', name: 'YNAB', slug: 'ynab', domain: 'youneedabudget.com', category: 'Finance', color: '003440' },
  { id: 'wealthfront', name: 'Wealthfront', slug: 'wealthfront', domain: 'wealthfront.com', category: 'Finance', color: '0055FF' },
  { id: 'betterment', name: 'Betterment', slug: 'betterment', domain: 'betterment.com', category: 'Finance', color: '00BDFF' },
  { id: 'acorns', name: 'Acorns', slug: 'acorns', domain: 'acorns.com', category: 'Finance', color: '00BB70' },
  { id: 'quickbooks', name: 'QuickBooks', slug: 'quickbooks', domain: 'quickbooks.intuit.com', category: 'Finance', color: '2CA01C' },
  { id: 'xero', name: 'Xero', slug: 'xero', domain: 'xero.com', category: 'Finance', color: '13B5EA' },
  { id: 'expensify', name: 'Expensify', slug: 'expensify', domain: 'expensify.com', category: 'Finance', color: '000000' },

  // Utilities
  { id: '1password', name: '1Password', slug: '1password', domain: '1password.com', category: 'Utilities', color: '0094FF' },
  { id: 'lastpass', name: 'LastPass', slug: 'lastpass', domain: 'lastpass.com', category: 'Utilities', color: 'D32D27' },
  { id: 'dashlane', name: 'Dashlane', slug: 'dashlane', domain: 'dashlane.com', category: 'Utilities', color: '0E353D' },
  { id: 'nordvpn', name: 'NordVPN', slug: 'nordvpn', domain: 'nordvpn.com', category: 'Utilities', color: '4687FF' },
  { id: 'expressvpn', name: 'ExpressVPN', slug: 'expressvpn', domain: 'expressvpn.com', category: 'Utilities', color: 'FF1C1C' },
  { id: 'surfshark', name: 'Surfshark', slug: 'surfshark', domain: 'surfshark.com', category: 'Utilities', color: '00D182' },
  { id: 'protonmail', name: 'Proton Mail', slug: 'protonmail', domain: 'proton.me', category: 'Utilities', color: '6D4AFF' },
  { id: 'mailchimp', name: 'Mailchimp', slug: 'mailchimp', domain: 'mailchimp.com', category: 'Utilities', color: 'FFE01B' },
  { id: 'sendgrid', name: 'SendGrid', slug: 'sendgrid', domain: 'sendgrid.com', category: 'Utilities', color: '1A82E2' },
  { id: 'grammarly', name: 'Grammarly', slug: 'grammarly', domain: 'grammarly.com', category: 'Utilities', color: '15CC71' },
  { id: 'bitwarden', name: 'Bitwarden', slug: 'bitwarden', domain: 'bitwarden.com', category: 'Utilities', color: '175DDC' },
  { id: 'mullvad', name: 'Mullvad VPN', slug: 'mullvad', domain: 'mullvad.net', category: 'Utilities', color: 'FF4500' },
  { id: 'cleanmymac', name: 'CleanMyMac X', slug: 'macpaw', domain: 'macpaw.com', category: 'Utilities', color: '000000' },
  { id: 'setapp', name: 'Setapp', slug: 'setapp', domain: 'setapp.com', category: 'Utilities', color: '000000' },
  { id: 'protonvpn', name: 'Proton VPN', slug: 'protonvpn', domain: 'protonvpn.com', category: 'Utilities', color: '6D4AFF' },
  { id: 'tunnelbear', name: 'TunnelBear', slug: 'tunnelbear', domain: 'tunnelbear.com', category: 'Utilities', color: '996633' },
  { id: 'malwarebytes', name: 'Malwarebytes', slug: 'malwarebytes', domain: 'malwarebytes.com', category: 'Utilities', color: '0094FF' },
  { id: 'kaspersky', name: 'Kaspersky', slug: 'kaspersky', domain: 'kaspersky.com', category: 'Utilities', color: '006D55' },
  { id: 'norton', name: 'Norton', slug: 'norton', domain: 'norton.com', category: 'Utilities', color: 'FFCC00' },
  { id: 'mcafee', name: 'McAfee', slug: 'mcafee', domain: 'mcafee.com', category: 'Utilities', color: 'C01818' },
  { id: 'adguard', name: 'AdGuard', slug: 'adguard', domain: 'adguard.com', category: 'Utilities', color: '68BC71' },
  { id: 'everhour', name: 'Everhour', slug: 'everhour', domain: 'everhour.com', category: 'Utilities', color: '24CC8A' },
  { id: 'toggl', name: 'Toggl Track', slug: 'toggltrack', domain: 'toggl.com', category: 'Utilities', color: 'E01B22' },


];

export const getLogoUrl = (domain: string, slug?: string, color?: string) => {
  // Primary: Clearbit (reliable HD logos)
  // Secondary: Simple Icons
  return `https://logo.clearbit.com/${domain}`;
};

export const getFallbackLogoUrl = (slug: string, color?: string) => {
  return `https://cdn.simpleicons.org/${slug}/${color || 'white'}`;
};


